import json, os

BASE = "/catalog-images/furniture"

def make_product(id, name, specs, stone, extra):
    desc = f"产品编号: {id.upper()}\n石材: {stone}\n规格: {specs}"
    return {
        "id": id,
        "name": name,
        "cover": f"{BASE}/page_{extra['pages'][0]:02d}.webp",
        "images": [f"{BASE}/page_{p:02d}.webp" for p in extra['pages']],
        "tagline": extra["tagline"],
        "description": f"{extra['tagline']}\n\n{desc}",
        "styles": extra["styles"],
        "specs": f"规格: {specs}\n石材品种: {stone}"
    }

console_table_products = [
    ("laf-a001", "Console Table LAF-A001", "1600×450×770mm", "Arabescato / 大花白", {"tagline": "简约线条感玄关桌，大花白大理石纹理飘逸", "styles": ["Console Table", "Contemporary"], "pages": [4]}),
    ("laf-a002", "Console Table LAF-A002", "1650×360×850mm", "Bvlgari Red / 宝格丽红", {"tagline": "宝格丽红的奢华气质，小空间玄关的理想选择", "styles": ["Console Table", "Luxury"], "pages": [4]}),
    ("laf-a003", "Console Table LAF-A003", "1650×360×850mm", "Beige Travertine / 米白洞", {"tagline": "米白洞石的温润质感，经典简约玄关桌", "styles": ["Console Table", "Contemporary"], "pages": [4]}),
    ("laf-a004", "Console Table LAF-A004", "1650×360×850mm", "Nero Marquina / 黑白根", {"tagline": "黑白根的深邃高贵，极简造型凸显石材本色", "styles": ["Console Table", "Modern"], "pages": [5]}),
    ("laf-a005", "Console Table LAF-A005", "1850×450×750mm", "Carrara White / 卡拉拉", {"tagline": "加长版设计，卡拉拉白的经典优雅", "styles": ["Console Table", "Classic"], "pages": [5]}),
    ("laf-a006", "Console Table LAF-A006", "400×160×800mm", "Beige Travertine / 米白洞", {"tagline": "纤薄窄款玄关桌，适合紧凑空间", "styles": ["Console Table", "Minimalist"], "pages": [5]}),
    ("laf-a007", "Console Table LAF-A007", "400×1600×800mm", "Shangrila Marble / 云中翡翠", {"tagline": "云中翡翠的独特纹理，修长比例的精致玄关桌", "styles": ["Console Table", "Contemporary"], "pages": [5]}),
    ("laf-a008", "Console Table LAF-A008", "1400×380×800mm", "Beige Travertine / 米白洞", {"tagline": "米白洞石自然肌理，中性色调百搭玄关桌", "styles": ["Console Table", "Contemporary"], "pages": [5]}),
    ("laf-a009", "Console Table LAF-A009", "2200×400×800mm", "Beige Travertine / 米白洞", {"tagline": "超长尺寸玄关桌，气派不凡", "styles": ["Console Table", "Contemporary"], "pages": [5]}),
    ("laf-a010", "Console Table LAF-A010", "1800×350×600mm", "Beige Travertine / 米白洞", {"tagline": "中长款玄关桌，搭配米白洞石的温润质感", "styles": ["Console Table", "Contemporary"], "pages": [5]}),
    ("laf-a011", "Console Table LAF-A011", "1200×300×750mm", "Red Travertine / 红洞石", {"tagline": "红洞石的温暖色泽，为玄关增添艺术气息", "styles": ["Console Table", "Contemporary"], "pages": [5]}),
    ("laf-a012", "Console Table LAF-A012", "1500×400×800mm", "Elephant White / 大象白", {"tagline": "大象白的纯净高雅，简洁线条的玄关桌", "styles": ["Console Table", "Minimalist"], "pages": [5]}),
]

dining_table_products = [
    ("laf-b001", "Dining Table LAF-B001", "900×1800×750mm", "Arabescato / 大花白", {"tagline": "大花白大理石餐桌，流畅纹理彰显自然之美", "styles": ["Dining Table", "Classic"], "pages": [7]}),
    ("laf-b002", "Dining Table LAF-B002", "900×1800×750mm", "Calacatta Viola Violet / 宝格丽紫", {"tagline": "宝格丽紫的奢华气质，六人位优雅餐桌", "styles": ["Dining Table", "Luxury"], "pages": [7]}),
    ("laf-b003", "Dining Table LAF-B003", "1600×450×750mm", "Calacatta Viola Violet / 宝格丽紫", {"tagline": "窄长造型餐桌，宝格丽紫紫色纹理引人注目", "styles": ["Dining Table", "Luxury"], "pages": [7]}),
    ("laf-b004", "Dining Table LAF-B004", "2200×800×760mm", "Noir Grand Antique / 宝格丽黑", {"tagline": "宝格丽黑沉稳大气，八人位大餐桌", "styles": ["Dining Table", "Modern"], "pages": [7]}),
    ("laf-b005", "Dining Table LAF-B005", "2200×800×760mm", "Arabescato / 大花白", {"tagline": "大花白大餐桌，经典纹理适配各种餐厅风格", "styles": ["Dining Table", "Classic"], "pages": [7]}),
    ("laf-b006", "Dining Table LAF-B006", "2200×800×760mm", "Verde Alpi / 普拉达绿", {"tagline": "普拉达绿的深邃绿意，为餐厅注入自然生机", "styles": ["Dining Table", "Contemporary"], "pages": [7]}),
    ("laf-b007", "Dining Table LAF-B007", "2200×800×760mm", "Shangrila Marble / 云中翡翠", {"tagline": "云中翡翠的独特纹理，打造视觉焦点", "styles": ["Dining Table", "Contemporary"], "pages": [7]}),
    ("laf-b008", "Dining Table LAF-B008", "2500×900×750mm", "Blue Crystal / 蓝水晶", {"tagline": "蓝水晶的梦幻蓝色调，超长餐桌彰显极致品味", "styles": ["Dining Table", "Luxury"], "pages": [7]}),
    ("laf-b009", "Dining Table LAF-B009", "2500×900×750mm", "Beige Travertine / 米白洞", {"tagline": "米白洞石大餐桌，温润中性调百搭餐厅", "styles": ["Dining Table", "Contemporary"], "pages": [7]}),
    ("laf-b010", "Dining Table LAF-B010", "2000×900×750mm", "Calacatta Viola Violet / 宝格丽紫", {"tagline": "宝格丽紫餐桌，紫色奢华纹理演绎用餐艺术", "styles": ["Dining Table", "Luxury"], "pages": [8]}),
    ("laf-b011", "Dining Table LAF-B011", "2000×900×750mm", "Calacatta Viola Violet / 宝格丽紫", {"tagline": "另一款宝格丽紫餐桌，纹理各异各有千秋", "styles": ["Dining Table", "Luxury"], "pages": [8]}),
    ("laf-b012", "Dining Table LAF-B012", "1600×850×750mm", "Verde Alpi / 普拉达绿", {"tagline": "适中尺寸的绿色大理石餐桌，绿色纹理独具魅力", "styles": ["Dining Table", "Contemporary"], "pages": [9]}),
    ("laf-b013", "Dining Table LAF-B013", "900×1800×750mm", "Beige Travertine / 米白洞", {"tagline": "米白洞石经典餐桌，自然优雅", "styles": ["Dining Table", "Contemporary"], "pages": [9]}),
    ("laf-b014", "Dining Table LAF-B014", "900×1800×750mm", "Beige Travertine / 米白洞", {"tagline": "同款米白洞石餐桌，不同纹理选择", "styles": ["Dining Table", "Contemporary"], "pages": [9]}),
    ("laf-b015", "Dining Table LAF-B015", "900×1800×750mm", "Beige Travertine / 米白洞", {"tagline": "米白洞石系列餐桌，温润耐用", "styles": ["Dining Table", "Contemporary"], "pages": [9]}),
    ("laf-b016", "Dining Table LAF-B016", "800×1600×750mm", "Beige Travertine / 米白洞", {"tagline": "紧凑尺寸餐桌，适合四至六人用餐", "styles": ["Dining Table", "Contemporary"], "pages": [9]}),
    ("laf-b017", "Dining Table LAF-B017", "600×1200×730mm", "Beige Travertine + Ultra Clear Glass / 米白洞+超白玻璃", {"tagline": "石材与玻璃的巧妙结合，现代感十足", "styles": ["Dining Table", "Modern"], "pages": [9]}),
    ("laf-b018", "Dining Table LAF-B018", "800×1600×750mm", "Palissandro White / 白金沙", {"tagline": "白金沙的细腻纹理，低调奢华的用餐体验", "styles": ["Dining Table", "Luxury"], "pages": [9]}),
    ("laf-b019", "Dining Table LAF-B019", "1700×1700×750mm", "Bianco Oro + Mosaic / 东方鱼肚白+马赛克剪画", {"tagline": "方形餐桌配马赛克拼花，东方鱼肚白尽显高雅", "styles": ["Dining Table", "Artistic"], "pages": [9]}),
    ("laf-b020", "Dining Table LAF-B020", "1600×1600×750mm", "Calacatta Viola Violet / 宝格丽紫", {"tagline": "方形宝格丽紫餐桌，奢华与优雅的完美结合", "styles": ["Dining Table", "Luxury"], "pages": [9]}),
]

coffee_table_products = [
    ("laf-c001", "Coffee Table LAF-C001", "910×910×380mm", "Calaccata / 大花白", {"tagline": "方形大花白咖啡桌，经典优雅", "styles": ["Coffee Table", "Classic"], "pages": [11]}),
    ("laf-c002", "Coffee Table LAF-C002", "900×900×300mm", "Beige Travertine / 米白洞", {"tagline": "低矮咖啡桌，米白洞石温润质感", "styles": ["Coffee Table", "Contemporary"], "pages": [11]}),
    ("laf-c003", "Coffee Table LAF-C003", "1270×1270×380mm", "Carrara White / 卡拉拉", {"tagline": "大尺寸卡拉拉白咖啡桌，宽敞台面", "styles": ["Coffee Table", "Classic"], "pages": [11]}),
    ("laf-c004", "Coffee Table LAF-C004", "1270×1270×380mm", "Shangrila Marble / 云中翡翠", {"tagline": "云中翡翠大方桌，独特翡翠纹理", "styles": ["Coffee Table", "Contemporary"], "pages": [11]}),
    ("laf-c005", "Coffee Table LAF-C005", "1270×1270×380mm", "Beige Travertine / 米白洞", {"tagline": "米白洞石大咖啡桌，百搭客厅", "styles": ["Coffee Table", "Contemporary"], "pages": [11]}),
    ("laf-c006", "Coffee Table LAF-C006", "700×1400×380mm", "Beige Travertine / 米白洞", {"tagline": "长方形咖啡桌，适合现代客厅布局", "styles": ["Coffee Table", "Contemporary"], "pages": [11]}),
    ("laf-c007", "Coffee Table LAF-C007", "700×1400×380mm", "Beige Travertine / 米白洞", {"tagline": "长款咖啡桌，纹理不同", "styles": ["Coffee Table", "Contemporary"], "pages": [11]}),
    ("laf-c008", "Coffee Table LAF-C008", "700×1200×320mm", "Beige Travertine / 米白洞", {"tagline": "中长款咖啡桌，适中高度", "styles": ["Coffee Table", "Contemporary"], "pages": [11]}),
    ("laf-c009", "Coffee Table LAF-C009", "1100×1100×380mm", "Beige Travertine / 米白洞", {"tagline": "方形咖啡桌，米白洞石的自然韵味", "styles": ["Coffee Table", "Contemporary"], "pages": [11]}),
    ("laf-c010", "Coffee Table LAF-C010", "800×700×380mm", "Carrara White / 卡拉拉", {"tagline": "偏置造型咖啡桌，设计感十足", "styles": ["Coffee Table", "Modern"], "pages": [12]}),
    ("laf-c011", "Coffee Table LAF-C011", "1000×1000×500mm", "Volakas / 爵士白", {"tagline": "高型咖啡桌，爵士白清雅纹理", "styles": ["Coffee Table", "Contemporary"], "pages": [12]}),
    ("laf-c012", "Coffee Table LAF-C012", "1000×1000×500mm", "Nero Marquina / 黑白根", {"tagline": "黑色高咖啡桌，沉稳大气", "styles": ["Coffee Table", "Modern"], "pages": [12]}),
    ("laf-c013", "Coffee Table LAF-C013", "1000×1000×380mm", "Verde Affai / 大花绿", {"tagline": "大花绿咖啡桌，绿色石材点亮空间", "styles": ["Coffee Table", "Contemporary"], "pages": [12]}),
    ("laf-c014", "Coffee Table LAF-C014", "700×1400×380mm", "Calaccata / 大花白", {"tagline": "大花白长桌，经典白色系", "styles": ["Coffee Table", "Classic"], "pages": [12]}),
    ("laf-c015", "Coffee Table LAF-C015", "700×1400×380mm", "Indian Green / 印度绿", {"tagline": "印度绿咖啡桌，绿色大理石纹理独特", "styles": ["Coffee Table", "Contemporary"], "pages": [12]}),
    ("laf-c016", "Coffee Table LAF-C016", "1000×1000×380mm", "Calacatta Viola Violet / 宝格丽紫", {"tagline": "宝格丽紫方形咖啡桌，紫色奢华", "styles": ["Coffee Table", "Luxury"], "pages": [12]}),
    ("laf-c017", "Coffee Table LAF-C017", "1100×500×500mm", "Elephant White + Wood / 大象白+木头", {"tagline": "石材与木材的融合，自然温暖的咖啡桌", "styles": ["Coffee Table", "Natural"], "pages": [12]}),
    ("laf-c018", "Coffee Table LAF-C018", "1000×1000×300mm", "Beige Travertine / 米白洞", {"tagline": "低矮方形米白洞石咖啡桌", "styles": ["Coffee Table", "Contemporary"], "pages": [12]}),
    ("laf-c019", "Coffee Table LAF-C019", "1000×1000×400mm", "Beige Travertine + Ultra Clear Glass / 米白洞+超白玻璃", {"tagline": "玻璃台面配米白洞石底座，现代感十足", "styles": ["Coffee Table", "Modern"], "pages": [13]}),
    ("laf-c020", "Coffee Table LAF-C020", "800×1400×380mm", "Beige Travertine / 米白洞", {"tagline": "长方形咖啡桌，米白洞石的自然纹理", "styles": ["Coffee Table", "Contemporary"], "pages": [13]}),
    ("laf-c021", "Coffee Table LAF-C021", "800×800×380mm", "Beige Travertine / 米白洞", {"tagline": "小方桌，灵活搭配", "styles": ["Coffee Table", "Contemporary"], "pages": [13]}),
    ("laf-c022", "Coffee Table LAF-C022", "700×1400×380mm", "Beige Travertine / 米白洞", {"tagline": "米白洞石长方形咖啡桌", "styles": ["Coffee Table", "Contemporary"], "pages": [13]}),
    ("laf-c023", "Coffee Table LAF-C023", "1000×1000×380mm", "Beige Travertine / 米白洞", {"tagline": "方形米白洞石咖啡桌", "styles": ["Coffee Table", "Contemporary"], "pages": [13]}),
    ("laf-c024", "Coffee Table LAF-C024", "800×800×380mm", "Crema Ultraman / 奥特曼米黄", {"tagline": "奥特曼米黄的温暖色调", "styles": ["Coffee Table", "Contemporary"], "pages": [13]}),
    ("laf-c025", "Coffee Table LAF-C025", "200×814×(380-450)mm", "Beige Travertine / 米白洞", {"tagline": "独特窄长造型咖啡桌", "styles": ["Coffee Table", "Modern"], "pages": [13]}),
    ("laf-c026", "Coffee Table LAF-C026", "800×800×380mm", "Beige Travertine / 米白洞", {"tagline": "小巧方形咖啡桌", "styles": ["Coffee Table", "Contemporary"], "pages": [13]}),
    ("laf-c027", "Coffee Table LAF-C027", "1200×1200×380mm", "Beige Travertine / 米白洞", {"tagline": "大号方形咖啡桌，米白洞石温润大气", "styles": ["Coffee Table", "Contemporary"], "pages": [13]}),
]

cube_coffee_table_products = [
    ("laf-d001", "Cube Coffee Table LAF-D001", "1000×600×300mm", "Shangrila Marble / 云中翡翠", {"tagline": "云中翡翠方几，独特纹理引人注目", "styles": ["Cube Coffee Table", "Contemporary"], "pages": [15]}),
    ("laf-d002", "Cube Coffee Table LAF-D002", "1000×600×300mm", "Arabescato / 大花白", {"tagline": "大花白方几，经典白色系", "styles": ["Cube Coffee Table", "Classic"], "pages": [15]}),
    ("laf-d003", "Cube Coffee Table LAF-D003", "1000×600×300mm", "Noir Grand Antique / 宝格丽黑", {"tagline": "宝格丽黑方几，深邃奢华", "styles": ["Cube Coffee Table", "Luxury"], "pages": [15]}),
    ("laf-d004", "Cube Coffee Table LAF-D004", "1000×600×300mm", "Calacatta Viola Violet / 宝格丽紫", {"tagline": "宝格丽紫方几，紫色奢华点缀", "styles": ["Cube Coffee Table", "Luxury"], "pages": [15]}),
    ("laf-d005", "Cube Coffee Table LAF-D005", "1000×600×300mm", "Sakura Pink Marble / 梦幻樱花", {"tagline": "梦幻樱花粉色调方几，温柔浪漫", "styles": ["Cube Coffee Table", "Contemporary"], "pages": [15]}),
    ("laf-d006", "Cube Coffee Table LAF-D006", "1000×600×300mm", "Rosso Norvegian / 挪威红", {"tagline": "挪威红方几，红色大理石热情奔放", "styles": ["Cube Coffee Table", "Contemporary"], "pages": [15]}),
    ("laf-d007", "Cube Coffee Table LAF-D007", "1000×600×300mm", "Cloud Grey / 云灰", {"tagline": "云灰方几，低调优雅的灰色调", "styles": ["Cube Coffee Table", "Minimalist"], "pages": [15]}),
    ("laf-d008", "Cube Coffee Table LAF-D008", "1000×600×300mm", "Jade Green Cloud Marble / 天空之境", {"tagline": "天空之境青绿色，清新雅致", "styles": ["Cube Coffee Table", "Contemporary"], "pages": [15]}),
    ("laf-d009", "Cube Coffee Table LAF-D009", "1000×600×300mm", "Ice Jade Marble / 冷翡翠", {"tagline": "冷翡翠方几，冰清玉洁", "styles": ["Cube Coffee Table", "Contemporary"], "pages": [15]}),
    ("laf-d010", "Cube Coffee Table LAF-D010", "1000×600×300mm", "Beige Travertine / 米白洞", {"tagline": "米白洞石方几，温润自然", "styles": ["Cube Coffee Table", "Contemporary"], "pages": [16]}),
    ("laf-d011", "Cube Coffee Table LAF-D011", "1000×600×300mm", "Nero Marquina / 黑白根", {"tagline": "黑白根方几，经典黑色", "styles": ["Cube Coffee Table", "Modern"], "pages": [16]}),
    ("laf-d012", "Cube Coffee Table LAF-D012", "700×1000×195mm", "Volakas White / 爵士白", {"tagline": "低矮宽型方几，爵士白清雅纹理", "styles": ["Cube Coffee Table", "Contemporary"], "pages": [16]}),
    ("laf-d013", "Cube Coffee Table LAF-D013", "400×400×400mm", "Sakura Pink Marble / 梦幻樱花", {"tagline": "小型方几，梦幻樱花的粉嫩色彩", "styles": ["Cube Coffee Table", "Contemporary"], "pages": [16]}),
    ("laf-d014", "Cube Coffee Table LAF-D014", "300×300×510mm", "Shangrila Marble / 云中翡翠", {"tagline": "小型高方几，云中翡翠纹理细腻", "styles": ["Cube Coffee Table", "Contemporary"], "pages": [17]}),
    ("laf-d015", "Cube Coffee Table LAF-D015", "300×300×510mm", "Ice Jade Marble / 冷翡翠", {"tagline": "冷翡翠柱形几", "styles": ["Cube Coffee Table", "Contemporary"], "pages": [17]}),
    ("laf-d016", "Cube Coffee Table LAF-D016", "300×300×510mm", "Rosa Portugallo / 烟粉", {"tagline": "烟粉色柱形几，柔和浪漫", "styles": ["Cube Coffee Table", "Contemporary"], "pages": [17]}),
    ("laf-d017", "Cube Coffee Table LAF-D017", "300×300×510mm", "Sakura Pink / 梦幻樱花", {"tagline": "梦幻樱花柱形几", "styles": ["Cube Coffee Table", "Contemporary"], "pages": [17]}),
    ("laf-d018", "Cube Coffee Table LAF-D018", "300×300×510mm", "Calacatta Viola Violet / 宝格丽紫", {"tagline": "宝格丽紫柱形几", "styles": ["Cube Coffee Table", "Luxury"], "pages": [17]}),
    ("laf-d019", "Cube Coffee Table LAF-D019", "300×300×510mm", "Beige Travertine / 米白洞", {"tagline": "米白洞柱形几", "styles": ["Cube Coffee Table", "Contemporary"], "pages": [17]}),
    ("laf-d020", "Cube Coffee Table LAF-D020", "300×300×1000mm", "Ice Jade Marble / 冷翡翠", {"tagline": "高柱形几，冷翡翠的冰透质感", "styles": ["Cube Coffee Table", "Contemporary"], "pages": [17]}),
    ("laf-d021", "Cube Coffee Table LAF-D021", "300×300×1000mm", "Volakas White / 爵士白", {"tagline": "爵士白高柱形几", "styles": ["Cube Coffee Table", "Contemporary"], "pages": [17]}),
    ("laf-d022", "Cube Coffee Table LAF-D022", "300×300×1000mm", "Carrara White / 卡拉拉", {"tagline": "卡拉拉白高柱形几", "styles": ["Cube Coffee Table", "Classic"], "pages": [17]}),
    ("laf-d023", "Cube Coffee Table LAF-D023", "300×300×1000mm", "Tiramisu Travertine / 提拉米苏", {"tagline": "提拉米苏色调高柱形几", "styles": ["Cube Coffee Table", "Contemporary"], "pages": [18]}),
    ("laf-d024", "Cube Coffee Table LAF-D024", "300×300×1000mm", "Carrara White / 卡拉拉", {"tagline": "卡拉拉白高柱形几", "styles": ["Cube Coffee Table", "Classic"], "pages": [18]}),
    ("laf-d025", "Cube Coffee Table LAF-D025", "300×300×1000mm", "Carrara White / 卡拉拉", {"tagline": "另一款卡拉拉白高柱形几", "styles": ["Cube Coffee Table", "Classic"], "pages": [18]}),
    ("laf-d026", "Cube Coffee Table LAF-D026", "250×250×910mm", "Beige Travertine / 米白洞", {"tagline": "纤细柱形几，灵活百搭", "styles": ["Cube Coffee Table", "Contemporary"], "pages": [18]}),
]

tall_coffee_table_products = [
    ("laf-e001", "Tall Coffee Table LAF-E001", "1200×1200×750mm", "Beige Travertine / 米白洞", {"tagline": "高型咖啡桌，吧台高度设计", "styles": ["Tall Coffee Table", "Contemporary"], "pages": [20]}),
    ("laf-e002", "Tall Coffee Table LAF-E002", "600×600×750mm", "Beige Travertine / 米白洞", {"tagline": "小巧高咖啡桌", "styles": ["Tall Coffee Table", "Contemporary"], "pages": [20]}),
    ("laf-e003", "Tall Coffee Table LAF-E003", "1200×1200×750mm", "Beige Travertine / 米白洞", {"tagline": "高咖啡桌，适合休闲吧台区域", "styles": ["Tall Coffee Table", "Contemporary"], "pages": [20]}),
    ("laf-e004", "Tall Coffee Table LAF-E004", "940×940×500mm", "Beige Travertine / 米白洞", {"tagline": "中高型咖啡桌", "styles": ["Tall Coffee Table", "Contemporary"], "pages": [20]}),
    ("laf-e005", "Tall Coffee Table LAF-E005", "1200×1200×750mm", "Beige Travertine / 米白洞", {"tagline": "米白洞石高咖啡桌系列", "styles": ["Tall Coffee Table", "Contemporary"], "pages": [20]}),
    ("laf-e006", "Tall Coffee Table LAF-E006", "1200×1200×750mm", "Beige Travertine / 米白洞", {"tagline": "同系列高咖啡桌", "styles": ["Tall Coffee Table", "Contemporary"], "pages": [20]}),
    ("laf-e007", "Tall Coffee Table LAF-E007", "1200×1200×750mm", "Beige Travertine / 米白洞", {"tagline": "高咖啡桌", "styles": ["Tall Coffee Table", "Contemporary"], "pages": [20]}),
    ("laf-e008", "Tall Coffee Table LAF-E008", "1200×1200×750mm", "Beige Travertine / 米白洞", {"tagline": "米白洞石高款", "styles": ["Tall Coffee Table", "Contemporary"], "pages": [20]}),
    ("laf-e009", "Tall Coffee Table LAF-E009", "1200×1200×750mm", "Beige Travertine / 米白洞", {"tagline": "高咖啡桌", "styles": ["Tall Coffee Table", "Contemporary"], "pages": [20]}),
    ("laf-e010", "Tall Coffee Table LAF-E010", "700×900×750mm", "Carrara White / 卡拉拉", {"tagline": "卡拉拉白高咖啡桌，经典优雅", "styles": ["Tall Coffee Table", "Classic"], "pages": [21]}),
    ("laf-e011", "Tall Coffee Table LAF-E011", "1200×1200×750mm", "Arabescato / 大花白", {"tagline": "大花白高咖啡桌", "styles": ["Tall Coffee Table", "Classic"], "pages": [21]}),
    ("laf-e012", "Tall Coffee Table LAF-E012", "1000×1000×750mm", "Calacatta Viola Violet / 宝格丽紫", {"tagline": "宝格丽紫高咖啡桌", "styles": ["Tall Coffee Table", "Luxury"], "pages": [21]}),
    ("laf-e013", "Tall Coffee Table LAF-E013", "1500×1500×750mm", "Indian Green / 印度绿", {"tagline": "印度绿大方桌，绿色惊艳", "styles": ["Tall Coffee Table", "Contemporary"], "pages": [21]}),
]

side_table_products = [
    ("laf-g001", "Side Table LAF-G001", "750×750×750mm", "Shangrila Marble + Carrara / 云中翡翠+卡拉拉", {"tagline": "双色拼接边桌，设计感十足", "styles": ["Side Table", "Modern"], "pages": [23]}),
    ("laf-g002", "Side Table LAF-G002", "350×350×470mm", "Cat'eye Green / 猫眼绿", {"tagline": "猫眼绿小边桌，绿色石材质感独特", "styles": ["Side Table", "Contemporary"], "pages": [23]}),
    ("laf-g003", "Side Table LAF-G003", "350×350×470mm", "Shangrila Marble / 云中翡翠", {"tagline": "云中翡翠小边桌", "styles": ["Side Table", "Contemporary"], "pages": [23]}),
    ("laf-g004", "Side Table LAF-G004", "350×350×470mm", "Noir Grand Antique / 宝格丽黑", {"tagline": "宝格丽黑小边桌", "styles": ["Side Table", "Modern"], "pages": [23]}),
    ("laf-g005", "Side Table LAF-G005", "400×400×450mm", "Arabescato / 大花白", {"tagline": "大花白小边桌，经典百搭", "styles": ["Side Table", "Classic"], "pages": [23]}),
    ("laf-g006", "Side Table LAF-G006", "300×300×430mm", "Guangxi White / 广西白", {"tagline": "广西白小边桌，简洁雅致", "styles": ["Side Table", "Minimalist"], "pages": [23]}),
    ("laf-g007", "Side Table LAF-G007", "300×300×550mm", "Nero Marquina / 黑白根", {"tagline": "高款黑白根小边桌", "styles": ["Side Table", "Modern"], "pages": [23]}),
    ("laf-g008", "Side Table LAF-G008", "457×457×508mm", "Carrara White / 卡拉拉", {"tagline": "卡拉拉白经典边桌", "styles": ["Side Table", "Classic"], "pages": [23]}),
    ("laf-g009", "Side Table LAF-G009", "457×457×508mm", "Beige Travertine / 米白洞", {"tagline": "米白洞石边桌", "styles": ["Side Table", "Contemporary"], "pages": [23]}),
    ("laf-g010", "Side Table LAF-G010", "395×395×400mm", "Beige Travertine / 米白洞", {"tagline": "米白洞石小方桌", "styles": ["Side Table", "Contemporary"], "pages": [24]}),
    ("laf-g011", "Side Table LAF-G011", "400×400×450mm", "Beige Travertine / 米白洞", {"tagline": "米白洞石边桌", "styles": ["Side Table", "Contemporary"], "pages": [24]}),
    ("laf-g012", "Side Table LAF-G012", "400×400×500mm", "Beige Travertine / 米白洞", {"tagline": "高款边桌", "styles": ["Side Table", "Contemporary"], "pages": [24]}),
    ("laf-g013", "Side Table LAF-G013", "600×600×600mm", "Beige Travertine / 米白洞", {"tagline": "大号方形边桌", "styles": ["Side Table", "Contemporary"], "pages": [24]}),
    ("laf-g014", "Side Table LAF-G014", "500×500×500mm", "Beige Travertine / 米白洞", {"tagline": "中型边桌", "styles": ["Side Table", "Contemporary"], "pages": [24]}),
    ("laf-g015", "Side Table LAF-G015", "500×500×330mm", "Beige Travertine / 米白洞", {"tagline": "矮款边桌", "styles": ["Side Table", "Contemporary"], "pages": [24]}),
    ("laf-g016", "Side Table LAF-G016", "500×500×460mm", "Beige Travertine / 米白洞", {"tagline": "中高边桌", "styles": ["Side Table", "Contemporary"], "pages": [24]}),
    ("laf-g017", "Side Table LAF-G017", "400×400×400mm", "Beige Travertine / 米白洞", {"tagline": "方形边桌", "styles": ["Side Table", "Contemporary"], "pages": [24]}),
    ("laf-g018", "Side Table LAF-G018", "400×400×500mm", "Beige Travertine / 米白洞", {"tagline": "高款边桌", "styles": ["Side Table", "Contemporary"], "pages": [24]}),
    ("laf-g019", "Side Table LAF-G019", "500×500×560mm", "Ariston / 雅士白", {"tagline": "雅士白高边桌，纯洁清雅", "styles": ["Side Table", "Classic"], "pages": [26]}),
    ("laf-g020", "Side Table LAF-G020", "400×400×560mm", "Arabescato / 大花白", {"tagline": "大花白高边桌", "styles": ["Side Table", "Classic"], "pages": [26]}),
    ("laf-g021", "Side Table LAF-G021", "500×500×750mm", "Red Travertine / 红洞石", {"tagline": "红洞石高边桌/吧台桌", "styles": ["Side Table", "Contemporary"], "pages": [26]}),
    ("laf-g022", "Side Table LAF-G022", "470×400×550mm", "Nero Marquina / 黑白根", {"tagline": "黑白根边桌", "styles": ["Side Table", "Modern"], "pages": [26]}),
    ("laf-g023", "Side Table LAF-G023", "470×400×550mm", "Indian Green / 印度绿", {"tagline": "印度绿边桌", "styles": ["Side Table", "Contemporary"], "pages": [26]}),
    ("laf-g024", "Side Table LAF-G024", "530×450×500mm", "Venato Carrara / 中花白", {"tagline": "中花白边桌", "styles": ["Side Table", "Classic"], "pages": [26]}),
    ("laf-g025", "Side Table LAF-G025", "470×400×550mm", "Arabescato / 大花白", {"tagline": "大花白边桌", "styles": ["Side Table", "Classic"], "pages": [26]}),
    ("laf-g026", "Side Table LAF-G026", "400×400×500mm", "Calacatta Viola Violet / 宝格丽紫", {"tagline": "宝格丽紫边桌", "styles": ["Side Table", "Luxury"], "pages": [26]}),
    ("laf-g027", "Side Table LAF-G027", "400×400×500mm", "Red Travertine / 红洞石", {"tagline": "红洞石边桌", "styles": ["Side Table", "Contemporary"], "pages": [26]}),
    ("laf-g028", "Side Table LAF-G028", "400×400×500mm", "Verde Alpi / 普拉达绿", {"tagline": "普拉达绿边桌", "styles": ["Side Table", "Contemporary"], "pages": [27]}),
    ("laf-g029", "Side Table LAF-G029", "400×400×500mm", "Calacatta Viola Violet / 宝格丽紫", {"tagline": "宝格丽紫边桌", "styles": ["Side Table", "Luxury"], "pages": [27]}),
    ("laf-g030", "Side Table LAF-G030", "350×350×500mm", "Rosa Levanto Marble / 紫罗红", {"tagline": "紫罗红小边桌", "styles": ["Side Table", "Contemporary"], "pages": [27]}),
    ("laf-g031", "Side Table LAF-G031", "350×350×500mm", "Calacatta Viola Violet / 宝格丽紫", {"tagline": "宝格丽紫小边桌", "styles": ["Side Table", "Luxury"], "pages": [27]}),
    ("laf-g032", "Side Table LAF-G032", "350×350×500mm", "Beige Travertine / 米白洞", {"tagline": "米白洞小边桌", "styles": ["Side Table", "Contemporary"], "pages": [27]}),
    ("laf-g033", "Side Table LAF-G033", "350×350×500mm", "Verde Alpi / 普拉达绿", {"tagline": "普拉达绿小边桌", "styles": ["Side Table", "Contemporary"], "pages": [27]}),
    ("laf-g034", "Side Table LAF-G034", "350×350×500mm", "Tiramisu Travertine / 提拉米苏", {"tagline": "提拉米苏色小边桌", "styles": ["Side Table", "Contemporary"], "pages": [27]}),
    ("laf-g035", "Side Table LAF-G035", "580×440×440mm", "Volakas White / 爵士白", {"tagline": "爵士白椭圆边桌", "styles": ["Side Table", "Contemporary"], "pages": [27]}),
    ("laf-g036", "Side Table LAF-G036", "580×440×440mm", "Beige Travertine / 米白洞", {"tagline": "米白洞椭圆边桌", "styles": ["Side Table", "Contemporary"], "pages": [27]}),
    ("laf-g037", "Side Table LAF-G037", "535×300×425mm", "Statuarietto Venato / 雪花白", {"tagline": "雪花白长形边桌", "styles": ["Side Table", "Classic"], "pages": [29]}),
    ("laf-g038", "Side Table LAF-G038", "300×300×500mm", "Beige Travertine / 米白洞", {"tagline": "小型边桌", "styles": ["Side Table", "Contemporary"], "pages": [29]}),
    ("laf-g039", "Side Table LAF-G039", "300×300×550mm", "Myanmar White / 缅甸白", {"tagline": "缅甸白高边桌", "styles": ["Side Table", "Classic"], "pages": [29]}),
    ("laf-g040", "Side Table LAF-G040", "300×300×500mm", "Carrara White / 卡拉拉", {"tagline": "卡拉拉白小边桌", "styles": ["Side Table", "Classic"], "pages": [29]}),
    ("laf-g041", "Side Table LAF-G041", "300×300×500mm", "Noir Grand Antique / 宝格丽黑", {"tagline": "宝格丽黑小边桌", "styles": ["Side Table", "Modern"], "pages": [29]}),
    ("laf-g042", "Side Table LAF-G042", "300×300×500mm", "Verde Alpi / 普拉达绿", {"tagline": "普拉达绿小边桌", "styles": ["Side Table", "Contemporary"], "pages": [29]}),
    ("laf-g043", "Side Table LAF-G043", "300×300×500mm", "Shangrila Marble / 云中翡翠", {"tagline": "云中翡翠小边桌", "styles": ["Side Table", "Contemporary"], "pages": [29]}),
    ("laf-g044", "Side Table LAF-G044", "500×500×460mm", "Calacatta Viola Turkey / 土耳其宝格丽", {"tagline": "土耳其宝格丽边桌", "styles": ["Side Table", "Luxury"], "pages": [29]}),
    ("laf-g045", "Side Table LAF-G045", "350×350×380mm", "Verde Alpi / 普拉达绿", {"tagline": "矮款绿色边桌", "styles": ["Side Table", "Contemporary"], "pages": [29]}),
    ("laf-g046", "Side Table LAF-G046", "420×420×500mm", "Nero Marquina + Glass / 黑白根+玻璃", {"tagline": "玻璃台面黑白根底座边桌", "styles": ["Side Table", "Modern"], "pages": [30]}),
    ("laf-g047", "Side Table LAF-G047", "454×454×560mm", "Arabescato Corchia / 鱼肚白", {"tagline": "鱼肚白高边桌", "styles": ["Side Table", "Classic"], "pages": [30]}),
    ("laf-g048", "Side Table LAF-G048", "454×454×560mm", "Orchid White / 君子兰", {"tagline": "君子兰白色边桌", "styles": ["Side Table", "Contemporary"], "pages": [30]}),
    ("laf-g049", "Side Table LAF-G049", "454×454×560mm", "Carrara Venato / 中花白", {"tagline": "中花白边桌", "styles": ["Side Table", "Classic"], "pages": [30]}),
    ("laf-g050", "Side Table LAF-G050", "454×454×560mm", "Ice Jade Marble / 冷翡翠", {"tagline": "冷翡翠边桌", "styles": ["Side Table", "Contemporary"], "pages": [30]}),
    ("laf-g051", "Side Table LAF-G051", "454×454×560mm", "China Emperador / 国产啡", {"tagline": "啡色边桌", "styles": ["Side Table", "Contemporary"], "pages": [30]}),
    ("laf-g052", "Side Table LAF-G052", "454×454×560mm", "Indian Green / 印度绿", {"tagline": "印度绿边桌", "styles": ["Side Table", "Contemporary"], "pages": [30]}),
    ("laf-g053", "Side Table LAF-G053", "454×454×560mm", "Azul Bahia / 景泰蓝", {"tagline": "景泰蓝蓝色边桌，色彩惊艳", "styles": ["Side Table", "Contemporary"], "pages": [30]}),
    ("laf-g054", "Side Table LAF-G054", "454×454×560mm", "Nero Marquina / 黑白根", {"tagline": "黑白根边桌", "styles": ["Side Table", "Modern"], "pages": [30]}),
]

sink_standing_products = [
    ("laf-h001", "Marble Sink LAF-H001", "1075×355×270mm", "Indian Green / 印度绿", {"tagline": "印度绿壁挂式面盆，独特绿色纹理", "styles": ["Marble Sink", "Contemporary"], "pages": [32]}),
    ("laf-h002", "Marble Sink LAF-H002", "600×400×900mm", "Noir Grand Antique / 宝格丽黑", {"tagline": "宝格丽黑立柱式面盆", "styles": ["Marble Sink", "Luxury"], "pages": [32]}),
    ("laf-h003", "Marble Sink LAF-H003", "600×400×900mm", "Carrara White / 卡拉拉", {"tagline": "卡拉拉白立柱式面盆", "styles": ["Marble Sink", "Classic"], "pages": [32]}),
    ("laf-h004", "Marble Sink LAF-H004", "600×400×900mm", "Verde Alpi / 普拉达绿", {"tagline": "普拉达绿立柱式面盆", "styles": ["Marble Sink", "Contemporary"], "pages": [32]}),
    ("laf-h005", "Marble Sink LAF-H005", "430×430×850mm", "Nero Marquina / 黑白根", {"tagline": "黑白根立柱面盆/台盆", "styles": ["Marble Sink", "Modern"], "pages": [32]}),
    ("laf-h006", "Marble Sink LAF-H006", "430×430×850mm", "Volakas White / 爵士白", {"tagline": "爵士白立柱面盆", "styles": ["Marble Sink", "Classic"], "pages": [32]}),
]

sink_products = [
    ("laf-j001", "Marble Sink LAF-J001", "430×430×850mm", "Volakas White / 爵士白", {"tagline": "爵士白立柱式洗手盆", "styles": ["Marble Sink", "Classic"], "pages": [34]}),
    ("laf-j002", "Marble Sink LAF-J002", "430×430×850mm", "Milas Lilac Marble / 香雪梅", {"tagline": "香雪梅立柱式洗手盆", "styles": ["Marble Sink", "Contemporary"], "pages": [34]}),
    ("laf-j003", "Marble Sink LAF-J003", "430×430×850mm", "Verde Alpi / 普拉达绿", {"tagline": "普拉达绿立柱式洗手盆", "styles": ["Marble Sink", "Contemporary"], "pages": [34]}),
    ("laf-j004", "Marble Sink LAF-J004", "430×430×850mm", "Nero Marquina / 黑白根", {"tagline": "黑白根立柱式洗手盆", "styles": ["Marble Sink", "Modern"], "pages": [34]}),
    ("laf-j005", "Marble Sink LAF-J005", "430×430×850mm", "Volakas White / 爵士白", {"tagline": "爵士白洗手盆", "styles": ["Marble Sink", "Classic"], "pages": [34]}),
    ("laf-j006", "Marble Sink LAF-J006", "400×400×850mm", "Shangrila Marble / 翡翠绿", {"tagline": "翡翠绿立柱式洗手盆", "styles": ["Marble Sink", "Contemporary"], "pages": [34]}),
    ("laf-j007", "Marble Sink LAF-J007", "400×400×850mm", "Volakas White / 爵士白", {"tagline": "爵士白洗手盆", "styles": ["Marble Sink", "Classic"], "pages": [34]}),
    ("laf-j008", "Marble Sink LAF-J008", "400×400×850mm", "Carrara White / 卡拉拉白", {"tagline": "卡拉拉白洗手盆", "styles": ["Marble Sink", "Classic"], "pages": [34]}),
    ("laf-j009", "Marble Sink LAF-J009", "400×400×850mm", "Milas Lilac Marble / 香雪梅", {"tagline": "香雪梅洗手盆", "styles": ["Marble Sink", "Contemporary"], "pages": [34]}),
    ("laf-j010", "Marble Sink LAF-J010", "430×430×850mm", "Pearl Stone / 鲍鱼石", {"tagline": "鲍鱼石洗手盆，珍珠光泽", "styles": ["Marble Sink", "Contemporary"], "pages": [35]}),
    ("laf-j011", "Marble Sink LAF-J011", "420×420×850mm", "Calacatta Viola Turkey / 土耳其宝格丽", {"tagline": "土耳其宝格丽洗手盆", "styles": ["Marble Sink", "Luxury"], "pages": [35]}),
    ("laf-j012", "Marble Sink LAF-J012", "400×400×850mm", "Carrara White / 卡拉拉白", {"tagline": "卡拉拉白洗手盆", "styles": ["Marble Sink", "Classic"], "pages": [35]}),
    ("laf-j013", "Marble Sink LAF-J013", "400×400×900mm", "Volakas White / 爵士白", {"tagline": "爵士白高款洗手盆", "styles": ["Marble Sink", "Classic"], "pages": [35]}),
    ("laf-j014", "Marble Sink LAF-J014", "540×540×850mm", "Carrara White / 卡拉拉白", {"tagline": "大号卡拉拉白洗手盆", "styles": ["Marble Sink", "Classic"], "pages": [35]}),
    ("laf-j015", "Marble Sink LAF-J015", "430×430×850mm", "Statuarietto Venato / 雪花白", {"tagline": "雪花白洗手盆", "styles": ["Marble Sink", "Classic"], "pages": [35]}),
    ("laf-j016", "Marble Sink LAF-J016", "400×400×850mm", "Milas Lilac Marble / 香雪梅", {"tagline": "香雪梅洗手盆", "styles": ["Marble Sink", "Contemporary"], "pages": [35]}),
    ("laf-j017", "Marble Sink LAF-J017", "430×430×850mm", "Carrara White / 卡拉拉白", {"tagline": "卡拉拉白洗手盆", "styles": ["Marble Sink", "Classic"], "pages": [35]}),
    ("laf-j018", "Marble Sink LAF-J018", "550×500×850mm", "Carrara White / 卡拉拉白", {"tagline": "椭圆卡拉拉白洗手盆", "styles": ["Marble Sink", "Classic"], "pages": [35]}),
    ("laf-j019", "Marble Sink LAF-J019", "450×400×850mm", "Carrara White / 古木纹", {"tagline": "古木纹洗手盆", "styles": ["Marble Sink", "Contemporary"], "pages": [36]}),
    ("laf-j020", "Marble Sink LAF-J020", "600×500×850mm", "Nero Marquina / 黑白根", {"tagline": "黑白根洗手盆", "styles": ["Marble Sink", "Modern"], "pages": [36]}),
    ("laf-j021", "Marble Sink LAF-J021", "430×430×850mm", "Carrara White / 卡拉拉白", {"tagline": "卡拉拉白洗手盆", "styles": ["Marble Sink", "Classic"], "pages": [36]}),
    ("laf-j022", "Marble Sink LAF-J022", "430×430×850mm", "Verde Affai / 大花绿", {"tagline": "大花绿洗手盆", "styles": ["Marble Sink", "Contemporary"], "pages": [36]}),
    ("laf-j023", "Marble Sink LAF-J023", "430×430×850mm", "Jade Green Cloud Marble / 天空之境", {"tagline": "天空之境青绿色洗手盆", "styles": ["Marble Sink", "Contemporary"], "pages": [36]}),
    ("laf-j024", "Marble Sink LAF-J024", "430×430×850mm", "Moca Crema / 白沙米黄", {"tagline": "白沙米黄洗手盆", "styles": ["Marble Sink", "Contemporary"], "pages": [36]}),
    ("laf-j025", "Marble Sink LAF-J025", "430×430×850mm", "Shangrila Marble / 云中翡翠", {"tagline": "云中翡翠洗手盆", "styles": ["Marble Sink", "Contemporary"], "pages": [36]}),
    ("laf-j026", "Marble Sink LAF-J026", "430×430×850mm", "Verde Alpi / 普拉达绿", {"tagline": "普拉达绿洗手盆", "styles": ["Marble Sink", "Contemporary"], "pages": [36]}),
    ("laf-j027", "Marble Sink LAF-J027", "430×430×850mm", "White Crystal Wood / 水晶木纹", {"tagline": "水晶木纹洗手盆", "styles": ["Marble Sink", "Contemporary"], "pages": [36]}),
    ("laf-j028", "Marble Sink LAF-J028", "430×430×850mm", "Guangxi White / 广西白", {"tagline": "广西白洗手盆", "styles": ["Marble Sink", "Classic"], "pages": [37]}),
    ("laf-j029", "Marble Sink LAF-J029", "430×430×850mm", "Elephant White / 大象白", {"tagline": "大象白洗手盆", "styles": ["Marble Sink", "Classic"], "pages": [37]}),
    ("laf-j030", "Marble Sink LAF-J030", "430×430×850mm", "Carrara White / 卡拉拉白", {"tagline": "卡拉拉白洗手盆", "styles": ["Marble Sink", "Classic"], "pages": [37]}),
    ("laf-j031", "Marble Sink LAF-J031", "430×430×850mm", "Red Travertine / 红洞", {"tagline": "红洞石洗手盆", "styles": ["Marble Sink", "Contemporary"], "pages": [37]}),
    ("laf-j032", "Marble Sink LAF-J032", "470×430×900mm", "Carrara White / 卡拉拉白", {"tagline": "卡拉拉白高款洗手盆", "styles": ["Marble Sink", "Classic"], "pages": [37]}),
    ("laf-j033", "Marble Sink LAF-J033", "470×430×900mm", "Elephant White / 大象白", {"tagline": "大象白高款洗手盆", "styles": ["Marble Sink", "Classic"], "pages": [37]}),
    ("laf-j034", "Marble Sink LAF-J034", "430×430×850mm", "Carrara White / 卡拉拉白", {"tagline": "卡拉拉白洗手盆", "styles": ["Marble Sink", "Classic"], "pages": [37]}),
    ("laf-j035", "Marble Sink LAF-J035", "400×400×850mm", "Volakas White / 爵士白", {"tagline": "爵士白洗手盆", "styles": ["Marble Sink", "Classic"], "pages": [37]}),
    ("laf-j036", "Marble Sink LAF-J036", "450×450×850mm", "Carrara White / 卡拉拉白", {"tagline": "卡拉拉白洗手盆", "styles": ["Marble Sink", "Classic"], "pages": [37]}),
    ("laf-j037", "Marble Sink LAF-J037", "400×400×850mm", "Volakas White / 爵士白", {"tagline": "爵士白洗手盆", "styles": ["Marble Sink", "Classic"], "pages": [38]}),
    ("laf-j038", "Marble Sink LAF-J038", "900×550×150mm", "Indian Green / 印度绿", {"tagline": "印度绿台上盆", "styles": ["Marble Sink", "Contemporary"], "pages": [38]}),
    ("laf-j039", "Marble Sink LAF-J039", "1000×500×100mm", "Carrara White / 卡拉拉白", {"tagline": "卡拉拉白台上盆", "styles": ["Marble Sink", "Classic"], "pages": [38]}),
    ("laf-j040", "Marble Sink LAF-J040", "1500×600×150mm", "Carrara White / 卡拉拉白", {"tagline": "超大卡拉拉白台上盆", "styles": ["Marble Sink", "Classic"], "pages": [38]}),
    ("laf-j041", "Marble Sink LAF-J041", "1400×500×100mm", "Guangxi White / 广西白", {"tagline": "广西白台上盆", "styles": ["Marble Sink", "Classic"], "pages": [38]}),
    ("laf-j042", "Marble Sink LAF-J042", "1200×500×150mm", "Volakas White / 爵士白", {"tagline": "爵士白台上盆", "styles": ["Marble Sink", "Classic"], "pages": [38]}),
    ("laf-j043", "Marble Sink LAF-J043", "800×600×150mm", "Volakas White / 爵士白", {"tagline": "爵士白台上盆", "styles": ["Marble Sink", "Classic"], "pages": [38]}),
    ("laf-j044", "Marble Sink LAF-J044", "1500×550×250mm", "Volakas White / 爵士白", {"tagline": "爵士白大台上盆", "styles": ["Marble Sink", "Classic"], "pages": [38]}),
    ("laf-j045", "Marble Sink LAF-J045", "1000×550×150mm", "Beige Travertine / 米黄洞石", {"tagline": "米黄洞石台上盆", "styles": ["Marble Sink", "Contemporary"], "pages": [38]}),
    ("laf-j046", "Marble Sink LAF-J046", "900×460×130mm", "Nero Marquina / 黑白根", {"tagline": "黑白根台上盆", "styles": ["Marble Sink", "Modern"], "pages": [40]}),
    ("laf-j047", "Marble Sink LAF-J047", "420×420×140mm", "Volakas White / 爵士白", {"tagline": "爵士白台上盆", "styles": ["Marble Sink", "Classic"], "pages": [40]}),
    ("laf-j048", "Marble Sink LAF-J048", "400×400×130mm", "Carrara White / 卡拉拉白", {"tagline": "卡拉拉白台上盆", "styles": ["Marble Sink", "Classic"], "pages": [40]}),
    ("laf-j049", "Marble Sink LAF-J049", "400×400×130mm", "Volakas White / 爵士白", {"tagline": "爵士白台上盆", "styles": ["Marble Sink", "Classic"], "pages": [40]}),
    ("laf-j050", "Marble Sink LAF-J050", "400×400×130mm", "Nero Marquina / 黑白根", {"tagline": "黑白根台上盆", "styles": ["Marble Sink", "Modern"], "pages": [40]}),
    ("laf-j051", "Marble Sink LAF-J051", "400×400×130mm", "Verde Alpi / 普拉达绿", {"tagline": "普拉达绿台上盆", "styles": ["Marble Sink", "Contemporary"], "pages": [40]}),
    ("laf-j052", "Marble Sink LAF-J052", "420×420×140mm", "Carrara White / 卡拉拉白", {"tagline": "卡拉拉白台上盆", "styles": ["Marble Sink", "Classic"], "pages": [40]}),
    ("laf-j053", "Marble Sink LAF-J053", "762×508×254mm", "Shangrila Marble / 云中翡翠", {"tagline": "云中翡翠台上盆", "styles": ["Marble Sink", "Contemporary"], "pages": [40]}),
    ("laf-j054", "Marble Sink LAF-J054", "450×300×150mm", "Brown Petrified Wood / 木化石", {"tagline": "木化石台上盆", "styles": ["Marble Sink", "Contemporary"], "pages": [40]}),
    ("laf-j055", "Marble Sink LAF-J055", "500×450×140mm", "Nero Marquina / 黑白根", {"tagline": "黑白根台上盆", "styles": ["Marble Sink", "Modern"], "pages": [41]}),
    ("laf-j056", "Marble Sink LAF-J056", "950×550×250mm", "Galala / 新西米", {"tagline": "新西米台上盆", "styles": ["Marble Sink", "Contemporary"], "pages": [41]}),
    ("laf-j057", "Marble Sink LAF-J057", "430×430×140mm", "Crema Marfil / 西米", {"tagline": "西米色台上盆", "styles": ["Marble Sink", "Contemporary"], "pages": [41]}),
    ("laf-j058", "Marble Sink LAF-J058", "500×350×130mm", "Porto Beige / 葡萄牙米黄", {"tagline": "葡萄牙米黄台上盆", "styles": ["Marble Sink", "Contemporary"], "pages": [41]}),
    ("laf-j059", "Marble Sink LAF-J059", "680×400×150mm", "Indian Green / 印度绿", {"tagline": "印度绿台上盆", "styles": ["Marble Sink", "Contemporary"], "pages": [41]}),
    ("laf-j060", "Marble Sink LAF-J060", "500×500×80mm", "Nero Marquina / 黑白根", {"tagline": "黑白根超薄台上盆", "styles": ["Marble Sink", "Modern"], "pages": [41]}),
    ("laf-j061", "Marble Sink LAF-J061", "500×500×80mm", "Volakas White / 爵士白", {"tagline": "爵士白超薄台上盆", "styles": ["Marble Sink", "Classic"], "pages": [41]}),
    ("laf-j062", "Marble Sink LAF-J062", "380×380×81mm", "White Travertine / 白洞石", {"tagline": "白洞石台上盆", "styles": ["Marble Sink", "Contemporary"], "pages": [41]}),
    ("laf-j063", "Marble Sink LAF-J063", "4000×400×130mm", "White Onyx / 白玉", {"tagline": "白玉超长台面盆", "styles": ["Marble Sink", "Luxury"], "pages": [41]}),
    ("laf-j064", "Marble Sink LAF-J064", "400×400×130mm", "Green Onyx / 青玉", {"tagline": "青玉台上盆", "styles": ["Marble Sink", "Luxury"], "pages": [42]}),
    ("laf-j065", "Marble Sink LAF-J065", "400×400×130mm", "Pink Onyx / 粉玉", {"tagline": "粉玉台上盆", "styles": ["Marble Sink", "Luxury"], "pages": [42]}),
    ("laf-j066", "Marble Sink LAF-J066", "400×400×130mm", "Milas Lilac Marble / 香雪梅", {"tagline": "香雪梅台上盆", "styles": ["Marble Sink", "Contemporary"], "pages": [42]}),
    ("laf-j067", "Marble Sink LAF-J067", "400×400×130mm", "Indian Green / 印度绿", {"tagline": "印度绿台上盆", "styles": ["Marble Sink", "Contemporary"], "pages": [42]}),
    ("laf-j068", "Marble Sink LAF-J068", "400×400×130mm", "Yellow Onyx / 黄玉", {"tagline": "黄玉台上盆", "styles": ["Marble Sink", "Luxury"], "pages": [42]}),
    ("laf-j069", "Marble Sink LAF-J069", "400×400×130mm", "Panda White / 熊猫白", {"tagline": "熊猫白台上盆", "styles": ["Marble Sink", "Contemporary"], "pages": [42]}),
    ("laf-j070", "Marble Sink LAF-J070", "400×400×130mm", "Beige Travertine / 米黄洞石", {"tagline": "米黄洞石台上盆", "styles": ["Marble Sink", "Contemporary"], "pages": [42]}),
    ("laf-j071", "Marble Sink LAF-J071", "400×400×130mm", "Elephant White / 大象白", {"tagline": "大象白台上盆", "styles": ["Marble Sink", "Classic"], "pages": [42]}),
    ("laf-j072", "Marble Sink LAF-J072", "400×400×130mm", "Noir Grand Antique / 宝格丽黑", {"tagline": "宝格丽黑台上盆", "styles": ["Marble Sink", "Luxury"], "pages": [42]}),
    ("laf-j073", "Marble Sink LAF-J073", "400×400×130mm", "Athens Gold / 雅典金花", {"tagline": "雅典金花台上盆", "styles": ["Marble Sink", "Contemporary"], "pages": [43]}),
    ("laf-j074", "Marble Sink LAF-J074", "400×400×130mm", "Beige Travertine / 米黄洞石", {"tagline": "米黄洞石台上盆", "styles": ["Marble Sink", "Contemporary"], "pages": [43]}),
    ("laf-j075", "Marble Sink LAF-J075", "580×380×110mm", "Statuarietto Venato / 雪花白", {"tagline": "雪花白台上盆", "styles": ["Marble Sink", "Classic"], "pages": [43]}),
    ("laf-j076", "Marble Sink LAF-J076", "450×320×130mm", "Nero Marquina / 黑白根", {"tagline": "黑白根台上盆", "styles": ["Marble Sink", "Modern"], "pages": [43]}),
    ("laf-j077", "Marble Sink LAF-J077", "580×380×120mm", "Nero Marquina / 黑白根", {"tagline": "黑白根椭圆台上盆", "styles": ["Marble Sink", "Modern"], "pages": [43]}),
    ("laf-j078", "Marble Sink LAF-J078", "500×400×130mm", "Nero Marquina / 黑白根", {"tagline": "黑白根台上盆", "styles": ["Marble Sink", "Modern"], "pages": [43]}),
    ("laf-j079", "Marble Sink LAF-J079", "580×380×110mm", "Nero Marquina / 黑白根", {"tagline": "黑白根台上盆", "styles": ["Marble Sink", "Modern"], "pages": [43]}),
    ("laf-j080", "Marble Sink LAF-J080", "600×400×130mm", "Nero Marquina / 黑白根", {"tagline": "黑白根大台上盆", "styles": ["Marble Sink", "Modern"], "pages": [43]}),
    ("laf-j081", "Marble Sink LAF-J081", "420×420×150mm", "Carrara White / 卡拉拉白", {"tagline": "卡拉拉白台上盆", "styles": ["Marble Sink", "Classic"], "pages": [43]}),
    ("laf-j082", "Marble Sink LAF-J082", "500×350×130mm", "Rain Forest Green / 雨林绿", {"tagline": "雨林绿台上盆", "styles": ["Marble Sink", "Contemporary"], "pages": [44]}),
    ("laf-j083", "Marble Sink LAF-J083", "450×430×210mm", "Menggu Black / 蒙古黑", {"tagline": "蒙古黑台上盆", "styles": ["Marble Sink", "Modern"], "pages": [44]}),
    ("laf-j084", "Marble Sink LAF-J084", "430×430×135mm", "Indian Green / 印度绿", {"tagline": "印度绿台上盆", "styles": ["Marble Sink", "Contemporary"], "pages": [44]}),
    ("laf-j085", "Marble Sink LAF-J085", "430×430×135mm", "Green Onyx / 青玉", {"tagline": "青玉台上盆", "styles": ["Marble Sink", "Luxury"], "pages": [44]}),
    ("laf-j086", "Marble Sink LAF-J086", "400×222×120mm", "Verde Affai / 大花绿", {"tagline": "大花绿台上盆", "styles": ["Marble Sink", "Contemporary"], "pages": [44]}),
    ("laf-j087", "Marble Sink LAF-J087", "600×350×150mm", "Carrara White / 卡拉拉白", {"tagline": "卡拉拉白台上盆", "styles": ["Marble Sink", "Classic"], "pages": [44]}),
    ("laf-j088", "Marble Sink LAF-J088", "450×350×130mm", "Pink Onyx / 粉玉", {"tagline": "粉玉台上盆", "styles": ["Marble Sink", "Luxury"], "pages": [44]}),
    ("laf-j089", "Marble Sink LAF-J089", "500×350×150mm", "Pink Onyx / 粉玉", {"tagline": "粉玉台上盆", "styles": ["Marble Sink", "Luxury"], "pages": [44]}),
    ("laf-j090", "Marble Sink LAF-J090", "430×430×135mm", "Pink Onyx / 粉玉", {"tagline": "粉玉台上盆", "styles": ["Marble Sink", "Luxury"], "pages": [44]}),
]

bathtub_products = [
    ("laf-k001", "Marble Bathtub LAF-K001", "1850×950×550mm", "Jade Green Cloud Marble / 天空之境", {"tagline": "天空之境大理石浴缸，翡翠般的质感", "styles": ["Marble Bathtub", "Luxury"], "pages": [46]}),
    ("laf-k002", "Marble Bathtub LAF-K002", "1900×900×550mm", "Palissandro White / 白金沙", {"tagline": "白金沙大理石浴缸，细腻纹理", "styles": ["Marble Bathtub", "Luxury"], "pages": [46]}),
    ("laf-k003", "Marble Bathtub LAF-K003", "1900×900×550mm", "Carrara White / 卡拉拉白", {"tagline": "卡拉拉白大理石浴缸，经典纯净", "styles": ["Marble Bathtub", "Classic"], "pages": [46]}),
    ("laf-k004", "Marble Bathtub LAF-K004", "1700×900×550mm", "Nero Marquina / 黑白根", {"tagline": "黑白根大理石浴缸，深邃高雅", "styles": ["Marble Bathtub", "Modern"], "pages": [46]}),
    ("laf-k005", "Marble Bathtub LAF-K005", "1900×900×550mm", "Shangrila Marble / 云中翡翠", {"tagline": "云中翡翠大理石浴缸，独特纹理", "styles": ["Marble Bathtub", "Luxury"], "pages": [46]}),
    ("laf-k006", "Marble Bathtub LAF-K006", "1700×900×550mm", "Crema Marfil / 西米", {"tagline": "西米色大理石浴缸", "styles": ["Marble Bathtub", "Classic"], "pages": [46]}),
    ("laf-k007", "Marble Bathtub LAF-K007", "1800×850×550mm", "Milas Lilac / 香雪梅", {"tagline": "香雪梅大理石浴缸", "styles": ["Marble Bathtub", "Contemporary"], "pages": [46]}),
    ("laf-k008", "Marble Bathtub LAF-K008", "1800×800×540mm", "Nero Marquina / 黑白根", {"tagline": "黑白根大理石浴缸", "styles": ["Marble Bathtub", "Modern"], "pages": [46]}),
    ("laf-k009", "Marble Bathtub LAF-K009", "1525×760×520mm", "Calacatta / 香雪梅", {"tagline": "紧凑款大理石浴缸", "styles": ["Marble Bathtub", "Classic"], "pages": [46]}),
]

all_products = []
for grp in [console_table_products, dining_table_products, coffee_table_products, cube_coffee_table_products, tall_coffee_table_products, side_table_products, sink_standing_products, sink_products, bathtub_products]:
    for item in grp:
        all_products.append(make_product(*item))

print(f"Total products: {len(all_products)}")
for p in all_products[:3]:
    print(f"  {p['id']}: {p['name']}")

# Save as JSON for later use
out = json.dumps(all_products, ensure_ascii=False, indent=2)
with open('C:/Users/Administrator/Documents/GitHub/kldstone.cn/furniture_products.json', 'w', encoding='utf-8') as f:
    f.write(out)
print("Done!")
